"$schema" = "https://starship.rs/config-schema.json"

[aws]
format = "\\[[$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)\\]"
symbol = "\uf0ef "

[azure]
format = "\\[[$symbol($subscription)]($style)\\]"
symbol = "\ue754 "

[battery]
charging_symbol = "\U000f0084 "
discharging_symbol = "\U000f0083 "
empty_symbol = "\U000f008e "
format = "\\[[$symbol$percentage]($style)\\]"
full_symbol = "\U000f0079 "
unknown_symbol = "\U000f0091 "

[buf]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\uf49d "

[bun]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue76f "

[c]
format = "\\[[$symbol($version(-$name))]($style)\\]"
symbol = "\ue61e "

[cmake]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue794 "

[cmd_duration]
format = "\\[[⏱ $duration]($style)\\]"

[cobol]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\uf013 "

[conda]
format = "\\[[$symbol$environment]($style)\\]"
symbol = "\ue715 "

[container]
format = "\\[[$symbol \\[$name\\]]($style)\\]"
symbol = "\uf4b7 "

[cpp]
format = "\\[[$symbol($version(-$name))]($style)\\]"
symbol = "\ue61d "

[crystal]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue62f "

[daml]
format = "\\[[$symbol($version)]($style)\\]"

[dart]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue64c "

[deno]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue7c0 "

[directory]
read_only = " \U000f033e"

[direnv]
format = "\\[[$symbol$loaded/$allowed]($style)\\]"
symbol = "\ue613 "

[docker_context]
format = "\\[[$symbol$context]($style)\\]"
symbol = "\uf308 "

[dotnet]
format = "\\[[$symbol($version)(🎯 $tfm)]($style)\\]"
symbol = "\ue77f "

[elixir]
format = "\\[[$symbol($version \\(OTP $otp_version\\))]($style)\\]"
symbol = "\ue62d "

[elm]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue62c "

[erlang]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\uf23f "

[fennel]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue6af "

[fortran]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue7de "

[fossil_branch]
format = "\\[[$symbol$branch]($style)\\]"
symbol = "\uf418 "

[fossil_metrics]
format = "\\[[+$added]($added_style)\\]\\[[-$deleted]($deleted_style)\\]"

[gcloud]
format = "\\[[$symbol$account(@$domain)(\\($region\\))]($style)\\]"
symbol = "\U000f11f6 "

[git_branch]
format = "\\[[$symbol$branch]($style)\\]"
symbol = "\uf418 "

[git_commit]
format = "\\[[\\($hash$tag\\)]($style)\\]"
tag_symbol = " \uf412 "

[git_metrics]
format = "\\[[+$added]($added_style)\\]\\[[-$deleted]($deleted_style)\\]"

[git_state]
format = "\\[[$state ($progress_current/$progress_total)]($style)\\]"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"

[gleam]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\uf005 "

[golang]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue627 "

[gradle]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue660 "

[guix_shell]
format = "\\[[$symbol]($style)\\]"
symbol = "\uf325 "

[haskell]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue777 "

[haxe]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue666 "

[helm]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue7fb "

[hg_branch]
format = "\\[[$symbol$branch]($style)\\]"
symbol = "\uf418 "

[hostname]
ssh_only = false
style = "bold green"
format = "[$ssh_symbol($hostname)]($style)\\] "
ssh_symbol = "\ueb01 "

[java]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue738 "

[jobs]
format = "\\[[$symbol$number]($style)\\]"

[julia]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue624 "

[kotlin]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue634 "

[kubernetes]
format = "\\[[$symbol$context( \\($namespace\\))]($style)\\]"
symbol = "\U000f10fe "

[localip]
format = "\\[[$localipv4]($style)\\]"

[lua]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue620 "

[maven]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue674 "

[memory_usage]
format = "\\[$symbol[$ram( | $swap)]($style)\\]"
symbol = "\U000f035b "

[meson]
format = "\\[[$symbol$project]($style)\\]"
symbol = "\U000f0537 "

[mise]
format = "\\[[$symbol$health]($style)\\]"

[mojo]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\U000f0238 "

[nats]
format = "\\[[$symbol$name]($style)\\]"
symbol = "\uf0e0 "

[netns]
format = "\\[[$symbol \\[$name\\]]($style)\\]"
symbol = "\U000f06f3 "

[nim]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue677 "

[nix_shell]
format = "\\[[$symbol$state( \\($name\\))]($style)\\]"
symbol = "\uf313 "

[nodejs]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue718 "

[ocaml]
format = "\\[[$symbol($version)(\\($switch_indicator$switch_name\\))]($style)\\]"
symbol = "\ue67a "

[odin]
format = "\\[[$symbol($version )]($style)\\]"
symbol = "\U000f07e2 "

[opa]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\uf132 "

[openstack]
format = "\\[[$symbol$cloud(\\($project\\))]($style)\\]"
symbol = "\ue856 "

[os]
format = "\\[[$symbol]($style)\\]"

[package]
format = "\\[[$symbol$version]($style)\\]"
symbol = "\U000f03d7 "

[perl]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue67e "

[php]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue608 "

[pijul_channel]
format = "\\[[$symbol$channel]($style)\\]"
symbol = "\uf418 "

[pixi]
format = "\\[[$symbol$version( $environment)]($style)\\]"
symbol = "\U000f03d7 "

[pulumi]
format = "\\[[$symbol$stack]($style)\\]"
symbol = "\ue873 "

[purescript]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue630 "

[python]
format = "\\[[${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\))]($style)\\]"
symbol = "\ue235 "

[quarto]
format = "\\[[$symbol($version)]($style)\\]"

[raku]
format = "\\[[$symbol($version-$vm_version)]($style)\\]"
symbol = "\U000f158a "

[red]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\U000f137c "

[rlang]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\U000f07d4 "

[ruby]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue791 "

[rust]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\U000f1617 "

[scala]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue737 "

[shell]
format = "\\[[$indicator]($style)\\]"

[shlvl]
symbol = "\U000f0e4d "

[singularity]
format = "\\[[$symbol\\[$env\\]]($style)\\]"
symbol = "\uf4b7 "

[solidity]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue8a6 "

[spack]
format = "\\[[$symbol$environment]($style)\\]"
symbol = "\ue8aa "

[status]
format = "\\[[$symbol$status]($style)\\]"
symbol = "\uf467 "

[sudo]
format = "\\[[as $symbol]($style)\\]"
symbol = "\uef01 "

[swift]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue755 "

[terraform]
format = "\\[[$symbol$workspace]($style)\\]"
symbol = "\ue69a "

[time]
format = "\\[[$time]($style)\\]"

[typst]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\uf37f "

[username]
show_always = true
style_user = "bold blue"
style_root = "black bold red"
format = "\\[[$user]($style)@"

[vagrant]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue8d0 "

[vcsh]
format = "\\[vcsh [$symbol$repo]($style)\\]"

[vlang]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue6ac "

[xmake]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue794 "

[zig]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "\ue6a9 "

[os.symbols]
AIX = "\ue8cc "
AlmaLinux = "\uf31d "
Alpaquita = "\ueaa2 "
Alpine = "\uf300 "
ALTLinux = "\uf31a "
Amazon = "\uf270 "
Android = "\uf17b "
AOSC = "\uf301 "
Arch = "\uf303 "
Artix = "\uf31f "
Bluefin = "\uf31a "
CachyOS = "\uf303 "
CentOS = "\uf304 "
Debian = "\uf306 "
DragonFly = "\ue28e "
Elementary = "\uf309 "
Emscripten = "\ue6a1 "
EndeavourOS = "\uf322 "
Fedora = "\uf30a "
FreeBSD = "\uf30c "
Garuda = "\uf337 "
Gentoo = "\uf30d "
HardenedBSD = "\U000f078c "
Illumos = "\uf326 "
InstantOS = "\uf31a "
Ios = "\U000f0037 "
Kali = "\uf327 "
Linux = "\uf31a "
Mabox = "\ueb29 "
Macos = "\uf302 "
Manjaro = "\uf312 "
Mariner = "\uf1cd "
MidnightBSD = "\uf186 "
Mint = "\uf30e "
NetBSD = "\uf024 "
NixOS = "\uf313 "
Nobara = "\uf380 "
OpenBSD = "\uf328 "
OpenCloudOS = "\uf31a "
openEuler = "\uf31a "
openSUSE = "\uf314 "
OracleLinux = "\U000f0ea1 "
PikaOS = "\uf31a "
Pop = "\uf32a "
Raspbian = "\uf315 "
Redhat = "\U000f111b "
RedHatEnterprise = "\U000f111b "
Redox = "\U000f0018 "
RockyLinux = "\uf32b "
Solus = "\uf32d "
SUSE = "\uf314 "
Ubuntu = "\uf31b "
Ultramarine = "\uf31a "
Unknown = "\uf22d "
Uos = "\uf321 "
Void = "\uf32e "
Windows = "\U000f0372 "
Zorin = "\uf32f "
